
server {
    # Nginx listens on HTTP port 80 inside the container.
    listen 80;

    # Accept requests for any hostname.
    server_name _;

    # Angular compiled files are stored here.
    root /usr/share/nginx/html;

    # Default file served when a directory is requested.
    index index.html;

    location / {
        # First try to find the requested file/directory.
        #
        # If it does not exist, return index.html.
        #
        # This is required for Angular client-side routing.
        #
        # Example:
        #   /dashboard
        #
        # Nginx does not have a physical /dashboard file.
        # Instead, it serves index.html and Angular's router
        # handles /dashboard.
        try_files $uri $uri/ /index.html;
    }
}