name: LedgerAxis CI/CD

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  BACKEND_IMAGE: jaydipaws/ledgeraxis-backend
  FRONTEND_IMAGE: jaydipaws/ledgeraxis-frontend

jobs:

  # BACKEND CI
  backend-ci:

    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v6

      # Install Node.js version required by backend
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      # Install backend dependencies
      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      # Run backend tests
      - name: Run backend tests
        working-directory: backend
        run: npm test

      # Build backend Docker image
      - name: Build backend Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: ledgeraxis-backend:test


  # FRONTEND CI
  frontend-ci:

    name: Frontend CI

    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v6

      # Install Node.js required by Angular
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      # Run frontend tests
      - name: Run frontend tests
        working-directory: frontend
        run: npm test -- --watch=false


        # Build Angular application
      - name: Build Angular application
        working-directory: frontend
        run: npm run build

      # Build frontend Docker image
      - name: Build frontend Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: ledgeraxis-frontend:test


  # DOCKER BUILD AND PUSH
  docker-publish:
    name: Build and Push Docker Images

    runs-on: ubuntu-latest

    needs:
      - backend-ci
      - frontend-ci

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:

      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v6

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Setup Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      # Generate Docker image metadata
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ env.BACKEND_IMAGE }}
            ${{ env.FRONTEND_IMAGE }}
          tags: |
            type=sha,prefix=git-
            type=raw,value=main

      # Build and push backend
      - name: Build and push backend
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:git-${{ github.sha }}
            ${{ env.BACKEND_IMAGE }}:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true

      # Build and push frontend
      - name: Build and push frontend
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:git-${{ github.sha }}
            ${{ env.FRONTEND_IMAGE }}:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true


          